import { describe, it } from 'https://deno.land/std@0.224.0/testing/bdd.ts';
import { assert } from 'https://deno.land/std@0.224.0/assert/mod.ts';
import { mapToStageWithRecipeSteps } from './mappers.ts';
import type { DatabaseRecipeSteps } from '../../dialectic-service/dialectic.interface.ts';
import { isDialecticStageRecipeStep } from './type-guards/type_guards.dialectic.ts';

describe('mapToStageWithRecipeSteps for synthesis stage', () => {

    it('should correctly map the "synthesis_prepare_pairwise_header" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-planner-pairwise',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-planner-pairwise',
                    step_key: 'synthesis_prepare_pairwise_header',
                    step_slug: 'prepare-pairwise-header',
                    step_name: 'Prepare Pairwise Header',
                    job_type: 'PLAN',
                    prompt_type: 'Planner',
                    prompt_template_id: 'prompt-synthesis-planner-pairwise',
                    output_type: 'HeaderContext',
                    granularity_strategy: 'pairwise_by_origin',
                    inputs_required: '[{"type":"document","slug":"thesis","document_key":"business_case","required":true},{"type":"document","slug":"antithesis","document_key":"business_case_critique","required":true,"section_header":"Business Case"},{"type":"document","slug":"thesis","document_key":"feature_spec","required":true},{"type":"document","slug":"antithesis","document_key":"feature_spec_critique","required":true,"section_header":"Feature Spec"},{"type":"document","slug":"thesis","document_key":"technical_approach","required":true},{"type":"document","slug":"antithesis","document_key":"technical_approach_critique","required":true,"section_header":"Technical Approach"},{"type":"document","slug":"thesis","document_key":"success_metrics","required":true},{"type":"document","slug":"antithesis","document_key":"success_metrics_critique","required":true,"section_header":"Success Metrics"}]',
                    inputs_relevance: '[{"document_key":"business_case","relevance":1.0},{"document_key":"business_case_critique","relevance":1.0},{"document_key":"feature_spec","relevance":1.0},{"document_key":"feature_spec_critique","relevance":1.0},{"document_key":"technical_approach","relevance":1.0},{"document_key":"technical_approach_critique","relevance":1.0},{"document_key":"success_metrics","relevance":1.0},{"document_key":"success_metrics_critique","relevance":1.0}]',
                    outputs_required: '{"header_context_artifact":{"type":"header_context","document_key":"header_context","artifact_class":"header_context","file_type":"json"},"system_materials":{"executive_summary":"concise overview of the comparison and synthesis plan","input_artifacts_summary":"summary of the Thesis proposal and its Antithesis critique","stage_rationale":"explain the pairwise comparison approach","progress_update":"for continuation turns, summarize completed vs pending comparisons; omit on first turn","validation_checkpoint":["key discrepancies identified","synthesis path is clear","alignment with original request validated","references and standards checked"],"quality_standards":["objective","thorough","constructive","actionable"]},"comparison_metadata":{"thesis_proposal_lineage_key":"<from thesis filename>","antithesis_critique_lineage_key":"<from antithesis filename>"},"context_for_documents":[{"document_key":"synthesis_business_case","content_to_include":{"strengths":[],"weaknesses":[],"recommendations":[],"synthesis":""}},{"document_key":"synthesis_feature_spec","content_to_include":{"strengths":[],"weaknesses":[],"recommendations":[],"synthesis":""}},{"document_key":"synthesis_technical_approach","content_to_include":{"strengths":[],"weaknesses":[],"recommendations":[],"synthesis":""}},{"document_key":"synthesis_success_metrics","content_to_include":{"strengths":[],"weaknesses":[],"recommendations":[],"synthesis":""}}]}',
                    parallel_group: null,
                    branch_key: null,
                    execution_order: 1,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Generate HeaderContext JSON to orchestrate pairwise comparison of Thesis artifacts and their critiques.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "synthesis_pairwise_business_case" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-pairwise-business-case',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-pairwise-business-case',
                    step_key: 'synthesis_pairwise_business_case',
                    step_slug: 'pairwise-business-case',
                    step_name: 'Pairwise Business Case',
                    job_type: 'EXECUTE',
                    prompt_type: 'Turn',
                    prompt_template_id: 'prompt-synthesis-pairwise-business-case',
                    output_type: 'RenderedDocument',
                    granularity_strategy: 'per_source_document',
                    inputs_required: '[{"type":"header_context","slug":"synthesis","document_key":"header_context","required":true},{"type":"document","slug":"thesis","document_key":"business_case","required":true},{"type":"document","slug":"antithesis","document_key":"business_case_critique","required":true}]',
                    inputs_relevance: '[{"document_key":"header_context","relevance":1.0},{"document_key":"business_case","relevance":1.0},{"document_key":"business_case_critique","relevance":1.0}]',
                    outputs_required: '{"documents":[{"document_key":"synthesis_business_case","template_filename":"synthesis_pairwise_business_case.md","artifact_class":"rendered_document","lineage_key":"<from thesis filename>","source_model_slug":"<from antithesis filename>","file_type":"markdown","content_to_include":{"strengths":[],"weaknesses":[],"recommendations":[],"synthesis":""}}],"files_to_generate":[{"template_filename":"synthesis_pairwise_business_case.md","from_document_key":"synthesis_business_case"}]}',
                    parallel_group: 2,
                    branch_key: 'synthesis_business_case',
                    execution_order: 2,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Compare the Business Case and its critique, then synthesize a result.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "synthesis_pairwise_feature_spec" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-pairwise-feature-spec',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-pairwise-feature-spec',
                    step_key: 'synthesis_pairwise_feature_spec',
                    step_slug: 'pairwise-feature-spec',
                    step_name: 'Pairwise Feature Spec',
                    job_type: 'EXECUTE',
                    prompt_type: 'Turn',
                    prompt_template_id: 'prompt-synthesis-pairwise-feature-spec',
                    output_type: 'RenderedDocument',
                    granularity_strategy: 'per_source_document',
                    inputs_required: '[{"type":"header_context","slug":"synthesis","document_key":"header_context","required":true},{"type":"document","slug":"thesis","document_key":"feature_spec","required":true},{"type":"document","slug":"antithesis","document_key":"feature_spec_critique","required":true}]',
                    inputs_relevance: '[{"document_key":"header_context","relevance":1.0},{"document_key":"feature_spec","relevance":1.0},{"document_key":"feature_spec_critique","relevance":1.0}]',
                    outputs_required: '{"documents":[{"document_key":"synthesis_feature_spec","template_filename":"synthesis_pairwise_feature_spec.md","artifact_class":"rendered_document","lineage_key":"<from thesis filename>","source_model_slug":"<from antithesis filename>","file_type":"markdown","content_to_include":{"strengths":[],"weaknesses":[],"recommendations":[],"synthesis":""}}],"files_to_generate":[{"template_filename":"synthesis_pairwise_feature_spec.md","from_document_key":"synthesis_feature_spec"}]}',
                    parallel_group: 2,
                    branch_key: 'synthesis_feature_spec',
                    execution_order: 2,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Compare the Feature Spec and its critique, then synthesize a result.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "synthesis_pairwise_technical_approach" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-pairwise-technical-approach',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-pairwise-technical-approach',
                    step_key: 'synthesis_pairwise_technical_approach',
                    step_slug: 'pairwise-technical-approach',
                    step_name: 'Pairwise Technical Approach',
                    job_type: 'EXECUTE',
                    prompt_type: 'Turn',
                    prompt_template_id: 'prompt-synthesis-pairwise-technical-approach',
                    output_type: 'RenderedDocument',
                    granularity_strategy: 'per_source_document',
                    inputs_required: '[{"type":"header_context","slug":"synthesis","document_key":"header_context","required":true},{"type":"document","slug":"thesis","document_key":"technical_approach","required":true},{"type":"document","slug":"antithesis","document_key":"technical_approach_critique","required":true}]',
                    inputs_relevance: '[{"document_key":"header_context","relevance":1.0},{"document_key":"technical_approach","relevance":1.0},{"document_key":"technical_approach_critique","relevance":1.0}]',
                    outputs_required: '{"documents":[{"document_key":"synthesis_technical_approach","template_filename":"synthesis_pairwise_technical_approach.md","artifact_class":"rendered_document","lineage_key":"<from thesis filename>","source_model_slug":"<from antithesis filename>","file_type":"markdown","content_to_include":{"strengths":[],"weaknesses":[],"recommendations":[],"synthesis":""}}],"files_to_generate":[{"template_filename":"synthesis_pairwise_technical_approach.md","from_document_key":"synthesis_technical_approach"}]}',
                    parallel_group: 2,
                    branch_key: 'synthesis_technical_approach',
                    execution_order: 2,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Compare the Technical Approach and its critique, then synthesize a result.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "synthesis_pairwise_success_metrics" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-pairwise-success-metrics',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-pairwise-success-metrics',
                    step_key: 'synthesis_pairwise_success_metrics',
                    step_slug: 'pairwise-success-metrics',
                    step_name: 'Pairwise Success Metrics',
                    job_type: 'EXECUTE',
                    prompt_type: 'Turn',
                    prompt_template_id: 'prompt-synthesis-pairwise-success-metrics',
                    output_type: 'RenderedDocument',
                    granularity_strategy: 'per_source_document',
                    inputs_required: '[{"type":"header_context","slug":"synthesis","document_key":"header_context","required":true},{"type":"document","slug":"thesis","document_key":"success_metrics","required":true},{"type":"document","slug":"antithesis","document_key":"success_metrics_critique","required":true}]',
                    inputs_relevance: '[{"document_key":"header_context","relevance":1.0},{"document_key":"success_metrics","relevance":1.0},{"document_key":"success_metrics_critique","relevance":1.0}]',
                    outputs_required: '{"documents":[{"document_key":"synthesis_success_metrics","template_filename":"synthesis_pairwise_success_metrics.md","artifact_class":"rendered_document","lineage_key":"<from thesis filename>","source_model_slug":"<from antithesis filename>","file_type":"markdown","content_to_include":{"strengths":[],"weaknesses":[],"recommendations":[],"synthesis":""}}],"files_to_generate":[{"template_filename":"synthesis_pairwise_success_metrics.md","from_document_key":"synthesis_success_metrics"}]}',
                    parallel_group: 2,
                    branch_key: 'synthesis_success_metrics',
                    execution_order: 2,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Compare the Success Metrics and its critique, then synthesize a result.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "synthesis_consolidate_feedback" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-planner-consolidate',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-planner-consolidate',
                    step_key: 'synthesis_consolidate_feedback',
                    step_slug: 'consolidate-feedback',
                    step_name: 'Consolidate Feedback',
                    job_type: 'PLAN',
                    prompt_type: 'Planner',
                    prompt_template_id: 'prompt-synthesis-planner-consolidate',
                    output_type: 'HeaderContext',
                    granularity_strategy: 'all_to_one',
                    inputs_required: '[{"type":"document","slug":"synthesis","document_key":"synthesis_business_case","required":true},{"type":"document","slug":"synthesis","document_key":"synthesis_feature_spec","required":true},{"type":"document","slug":"synthesis","document_key":"synthesis_technical_approach","required":true},{"type":"document","slug":"synthesis","document_key":"synthesis_success_metrics","required":true},{"type":"feedback","slug":"synthesis","document_key":"synthesis_business_case","required":false},{"type":"feedback","slug":"synthesis","document_key":"synthesis_feature_spec","required":false},{"type":"feedback","slug":"synthesis","document_key":"synthesis_technical_approach","required":false},{"type":"feedback","slug":"synthesis","document_key":"synthesis_success_metrics","required":false}]',
                    inputs_relevance: '[{"document_key":"synthesis_business_case","relevance":1.0},{"document_key":"synthesis_feature_spec","relevance":1.0},{"document_key":"synthesis_technical_approach","relevance":1.0},{"document_key":"synthesis_success_metrics","relevance":1.0},{"document_key":"synthesis_business_case","type":"feedback","relevance":1.0},{"document_key":"synthesis_feature_spec","type":"feedback","relevance":1.0},{"document_key":"synthesis_technical_approach","type":"feedback","relevance":1.0},{"document_key":"synthesis_success_metrics","type":"feedback","relevance":1.0}]',
                    outputs_required: '{"header_context_artifact":{"type":"header_context","document_key":"header_context","artifact_class":"header_context","file_type":"json"},"system_materials":{"executive_summary":"concise overview of the final synthesis plan","input_artifacts_summary":"summary of pairwise comparisons and user feedback","stage_rationale":"explain the final synthesis approach","progress_update":"for continuation turns, summarize completed vs pending synthesis; omit on first turn","validation_checkpoint":["all feedback incorporated","final proposal is coherent and complete","alignment with original request re-validated","references and standards checked"],"quality_standards":["objective","thorough","constructive","actionable"]},"synthesis_metadata":{"pairwise_comparison_lineage_keys":"<from all synthesis pairwise filenames>"},"context_for_documents":[{"document_key":"final_business_case","content_to_include":{}},{"document_key":"final_feature_spec","content_to_include":{}},{"document_key":"final_technical_approach","content_to_include":{}},{"document_key":"final_success_metrics","content_to_include":{}}]}',
                    parallel_group: null,
                    branch_key: null,
                    execution_order: 3,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Generate HeaderContext JSON to orchestrate the final synthesis of all artifacts.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "synthesis_synthesize_business_case" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-final-business-case',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-final-business-case',
                    step_key: 'synthesis_synthesize_business_case',
                    step_slug: 'synthesize-business-case',
                    step_name: 'Synthesize Business Case',
                    job_type: 'EXECUTE',
                    prompt_type: 'Turn',
                    prompt_template_id: 'prompt-synthesis-final-business-case',
                    output_type: 'RenderedDocument',
                    granularity_strategy: 'per_source_document',
                    inputs_required: '[{"type":"header_context","slug":"synthesis","document_key":"header_context","required":true},{"type":"document","slug":"synthesis","document_key":"synthesis_business_case","required":true},{"type":"feedback","slug":"synthesis","document_key":"synthesis_business_case","required":false}]',
                    inputs_relevance: '[{"document_key":"header_context","relevance":1.0},{"document_key":"synthesis_business_case","relevance":1.0},{"document_key":"synthesis_business_case","type":"feedback","relevance":1.0}]',
                    outputs_required: '{"documents":[{"document_key":"final_business_case","template_filename":"final_business_case.md","artifact_class":"rendered_document","lineage_key":"<from synthesis filename>","source_model_slug":"<from synthesis feedback>","file_type":"markdown","content_to_include":{}}],"files_to_generate":[{"template_filename":"final_business_case.md","from_document_key":"final_business_case"}]}',
                    parallel_group: 4,
                    branch_key: 'final_business_case',
                    execution_order: 4,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Produce the final, synthesized Business Case.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "synthesis_synthesize_feature_spec" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-final-feature-spec',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-final-feature-spec',
                    step_key: 'synthesis_synthesize_feature_spec',
                    step_slug: 'synthesize-feature-spec',
                    step_name: 'Synthesize Feature Spec',
                    job_type: 'EXECUTE',
                    prompt_type: 'Turn',
                    prompt_template_id: 'prompt-synthesis-final-feature-spec',
                    output_type: 'RenderedDocument',
                    granularity_strategy: 'per_source_document',
                    inputs_required: '[{"type":"header_context","slug":"synthesis","document_key":"header_context","required":true},{"type":"document","slug":"synthesis","document_key":"synthesis_feature_spec","required":true},{"type":"feedback","slug":"synthesis","document_key":"synthesis_feature_spec","required":false}]',
                    inputs_relevance: '[{"document_key":"header_context","relevance":1.0},{"document_key":"synthesis_feature_spec","relevance":1.0},{"document_key":"synthesis_feature_spec","type":"feedback","relevance":1.0}]',
                    outputs_required: '{"documents":[{"document_key":"final_feature_spec","template_filename":"final_feature_spec.md","artifact_class":"rendered_document","lineage_key":"<from synthesis filename>","source_model_slug":"<from synthesis feedback>","file_type":"markdown","content_to_include":{}}],"files_to_generate":[{"template_filename":"final_feature_spec.md","from_document_key":"final_feature_spec"}]}',
                    parallel_group: 4,
                    branch_key: 'final_feature_spec',
                    execution_order: 4,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Produce the final, synthesized Feature Spec.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "synthesis_synthesize_technical_approach" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-final-technical-approach',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-final-technical-approach',
                    step_key: 'synthesis_synthesize_technical_approach',
                    step_slug: 'synthesize-technical-approach',
                    step_name: 'Synthesize Technical Approach',
                    job_type: 'EXECUTE',
                    prompt_type: 'Turn',
                    prompt_template_id: 'prompt-synthesis-final-technical-approach',
                    output_type: 'RenderedDocument',
                    granularity_strategy: 'per_source_document',
                    inputs_required: '[{"type":"header_context","slug":"synthesis","document_key":"header_context","required":true},{"type":"document","slug":"synthesis","document_key":"synthesis_technical_approach","required":true},{"type":"feedback","slug":"synthesis","document_key":"synthesis_technical_approach","required":false}]',
                    inputs_relevance: '[{"document_key":"header_context","relevance":1.0},{"document_key":"synthesis_technical_approach","relevance":1.0},{"document_key":"synthesis_technical_approach","type":"feedback","relevance":1.0}]',
                    outputs_required: '{"documents":[{"document_key":"final_technical_approach","template_filename":"final_technical_approach.md","artifact_class":"rendered_document","lineage_key":"<from synthesis filename>","source_model_slug":"<from synthesis feedback>","file_type":"markdown","content_to_include":{}}],"files_to_generate":[{"template_filename":"final_technical_approach.md","from_document_key":"final_technical_approach"}]}',
                    parallel_group: 4,
                    branch_key: 'final_technical_approach',
                    execution_order: 4,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Produce the final, synthesized Technical Approach.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "synthesis_synthesize_success_metrics" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-final-success-metrics',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-final-success-metrics',
                    step_key: 'synthesis_synthesize_success_metrics',
                    step_slug: 'synthesize-success-metrics',
                    step_name: 'Synthesize Success Metrics',
                    job_type: 'EXECUTE',
                    prompt_type: 'Turn',
                    prompt_template_id: 'prompt-synthesis-final-success-metrics',
                    output_type: 'RenderedDocument',
                    granularity_strategy: 'per_source_document',
                    inputs_required: '[{"type":"header_context","slug":"synthesis","document_key":"header_context","required":true},{"type":"document","slug":"synthesis","document_key":"synthesis_success_metrics","required":true},{"type":"feedback","slug":"synthesis","document_key":"synthesis_success_metrics","required":false}]',
                    inputs_relevance: '[{"document_key":"header_context","relevance":1.0},{"document_key":"synthesis_success_metrics","relevance":1.0},{"document_key":"synthesis_success_metrics","type":"feedback","relevance":1.0}]',
                    outputs_required: '{"documents":[{"document_key":"final_success_metrics","template_filename":"final_success_metrics.md","artifact_class":"rendered_document","lineage_key":"<from synthesis filename>","source_model_slug":"<from synthesis feedback>","file_type":"markdown","content_to_include":{}}],"files_to_generate":[{"template_filename":"final_success_metrics.md","from_document_key":"final_success_metrics"}]}',
                    parallel_group: 4,
                    branch_key: 'final_success_metrics',
                    execution_order: 4,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Produce the final, synthesized Success Metrics.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "generate_final_synthesis_header" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-final-header',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-final-header',
                    step_key: 'generate_final_synthesis_header',
                    step_slug: 'generate-final-synthesis-header',
                    step_name: 'Generate Final Synthesis Header',
                    job_type: 'PLAN',
                    prompt_type: 'Planner',
                    prompt_template_id: 'prompt-synthesis-final-header-planner',
                    output_type: 'HeaderContext',
                    granularity_strategy: 'all_to_one',
                    inputs_required: '[{"type":"seed_prompt","slug":"synthesis","document_key":"seed_prompt","required":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_business_case","required":true,"multiple":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_feature_spec","required":true,"multiple":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_technical_approach","required":true,"multiple":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_success_metrics","required":true,"multiple":true}]',
                    inputs_relevance: '[{"document_key":"seed_prompt","slug":"synthesis","relevance":0.6},{"document_key":"synthesis_document_business_case","slug":"synthesis","relevance":1.0},{"document_key":"synthesis_document_feature_spec","slug":"synthesis","relevance":0.95},{"document_key":"synthesis_document_technical_approach","slug":"synthesis","relevance":0.95},{"document_key":"synthesis_document_success_metrics","slug":"synthesis","relevance":0.9}]',
                    outputs_required: '{"system_materials":{"executive_summary":"Outline/index of all outputs in this response and how they connect to the objective","input_artifacts_summary":"Succinct summary of prior proposals, critiques, and user feedback included in this synthesis","stage_rationale":"Decision record explaining how signals and critiques informed selections, how conflicts were resolved, gaps were filled, and why chosen approaches best meet constraints","progress_update":"For continuation turns, summarize what is complete vs remaining; omit on first turn","signal_sources":["synthesis_document_business_case","synthesis_document_feature_spec","synthesis_document_technical_approach","synthesis_document_success_metrics"],"decision_criteria":["feasibility","complexity","security","performance","maintainability","scalability","cost","time_to_market","compliance_risk","alignment_with_constraints"],"validation_checkpoint":["requirements addressed","best practices applied","feasible & compliant","references integrated"],"quality_standards":["security-first","maintainable","scalable","performance-aware"]},"header_context_artifact":{"type":"header_context","document_key":"header_context","artifact_class":"header_context","file_type":"json"},"context_for_documents":[{"document_key":"prd","content_to_include":{"executive_summary":"","mvp_description":"","user_problem_validation":"","market_opportunity":"","competitive_analysis":"","differentiation_&_value_proposition":"","risks_&_mitigation":"","strengths":[],"weaknesses":[],"opportunities":[],"threats":[],"feature_scope":[],"features":[{"feature_name":"","feature_objective":"","user_stories":[],"acceptance_criteria":[],"dependencies":[],"success_metrics":[],"risk_mitigation":"","open_questions":"","tradeoffs":[]}],"feasibility_insights":[],"non_functional_alignment":[],"score_adjustments":[],"outcome_alignment":"","north_star_metric":"","primary_kpis":[],"leading_indicators":[],"lagging_indicators":[],"guardrails":[],"measurement_plan":"","risk_signals":[],"resolved_positions":[],"open_questions":[],"next_steps":"","proposal_references":[],"release_plan":[],"assumptions":[],"open_decisions":[],"implementation_risks":[],"stakeholder_communications":[]}},{"document_key":"system_architecture_overview","content_to_include":{"architecture_summary":"","architecture":"","services":[],"components":[],"data_flows":[],"interfaces":[],"integration_points":[],"dependency_resolution":[],"conflict_flags":[],"sequencing":"","risk_mitigations":[],"risk_signals":[],"security_measures":[],"observability_strategy":[],"scalability_plan":[],"resilience_strategy":[],"compliance_controls":[],"open_questions":[]}},{"document_key":"tech_stack_recommendations","content_to_include":{"frontend_stack":{},"backend_stack":{},"data_platform":{},"devops_tooling":{},"security_tooling":{},"shared_libraries":[],"third_party_services":[],"components":[{"component_name":"","recommended_option":"","rationale":"","alternatives":[],"tradeoffs":[],"risk_signals":[],"integration_requirements":[],"operational_owners":[],"migration_plan":[]}],"open_questions":[],"next_steps":[]}}],"files_to_generate":[{"template_filename":"synthesis_product_requirements_document.md","from_document_key":"prd"},{"template_filename":"synthesis_system_architecture_overview.md","from_document_key":"system_architecture_overview"},{"template_filename":"synthesis_tech_stack_recommendations.md","from_document_key":"tech_stack_recommendations"}]}',
                    parallel_group: null,
                    branch_key: null,
                    execution_order: 4,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Generate the final HeaderContext for Synthesis stage deliverables.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "prd" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-prd',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-prd',
                    step_key: 'prd',
                    step_slug: 'render-prd',
                    step_name: 'Render Final PRD',
                    job_type: 'EXECUTE',
                    prompt_type: 'Turn',
                    prompt_template_id: 'prompt-synthesis-prd-turn',
                    output_type: 'RenderedDocument',
                    granularity_strategy: 'all_to_one',
                    inputs_required: '[{"type":"header_context","slug":"synthesis","document_key":"header_context","required":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_business_case","required":true,"multiple":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_feature_spec","required":true,"multiple":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_technical_approach","required":true,"multiple":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_success_metrics","required":true,"multiple":true}]',
                    inputs_relevance: '[{"document_key":"header_context","slug":"synthesis","relevance":1.0},{"document_key":"synthesis_document_business_case","slug":"synthesis","relevance":1.0},{"document_key":"synthesis_document_feature_spec","slug":"synthesis","relevance":0.9},{"document_key":"synthesis_document_technical_approach","slug":"synthesis","relevance":0.85},{"document_key":"synthesis_document_success_metrics","slug":"synthesis","relevance":0.8}]',
                    outputs_required: '{"documents":[{"document_key":"prd","template_filename":"synthesis_product_requirements_document.md","artifact_class":"rendered_document","file_type":"markdown","content_to_include":{"executive_summary":"","mvp_description":"","user_problem_validation":"","market_opportunity":"","competitive_analysis":"","differentiation_&_value_proposition":"","risks_&_mitigation":"","strengths":[],"weaknesses":[],"opportunities":[],"threats":[],"feature_scope":[],"features":[{"feature_name":"","feature_objective":"","user_stories":[],"acceptance_criteria":[],"dependencies":[],"success_metrics":[],"risk_mitigation":"","open_questions":"","tradeoffs":[]}],"feasibility_insights":[],"non_functional_alignment":[],"score_adjustments":[],"outcome_alignment":"","north_star_metric":"","primary_kpis":[],"leading_indicators":[],"lagging_indicators":[],"guardrails":[],"measurement_plan":"","risk_signals":[],"resolved_positions":[],"open_questions":[],"next_steps":"","proposal_references":[],"release_plan":[],"assumptions":[],"open_decisions":[],"implementation_risks":[],"stakeholder_communications":[]}}]}',
                    parallel_group: 5,
                    branch_key: 'prd',
                    execution_order: 5,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Renders the final Product Requirements Document from the consolidated synthesis artifacts.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "system_architecture_overview" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-arch-overview',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-arch-overview',
                    step_key: 'system_architecture_overview',
                    step_slug: 'render-system-architecture-overview',
                    step_name: 'Render Final System Architecture Overview',
                    job_type: 'EXECUTE',
                    prompt_type: 'Turn',
                    prompt_template_id: 'prompt-synthesis-system-arch-turn',
                    output_type: 'RenderedDocument',
                    granularity_strategy: 'all_to_one',
                    inputs_required: '[{"type":"header_context","slug":"synthesis","document_key":"header_context","required":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_technical_approach","required":true,"multiple":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_feature_spec","required":true,"multiple":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_business_case","required":true,"multiple":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_success_metrics","required":true,"multiple":true}]',
                    inputs_relevance: '[{"document_key":"header_context","slug":"synthesis","relevance":1.0},{"document_key":"synthesis_document_technical_approach","slug":"synthesis","relevance":1.0},{"document_key":"synthesis_document_feature_spec","slug":"synthesis","relevance":0.9},{"document_key":"synthesis_document_business_case","slug":"synthesis","relevance":0.82},{"document_key":"synthesis_document_success_metrics","slug":"synthesis","relevance":0.78}]',
                    outputs_required: '{"documents":[{"document_key":"system_architecture_overview","template_filename":"synthesis_system_architecture_overview.md","artifact_class":"rendered_document","file_type":"markdown","content_to_include":{"architecture_summary":"","architecture":"","services":[],"components":[],"data_flows":[],"interfaces":[],"integration_points":[],"dependency_resolution":[],"conflict_flags":[],"sequencing":"","risk_mitigations":[],"risk_signals":[],"security_measures":[],"observability_strategy":[],"scalability_plan":[],"resilience_strategy":[],"compliance_controls":[],"open_questions":[]}}]}',
                    parallel_group: 5,
                    branch_key: 'system_architecture_overview',
                    execution_order: 5,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Renders the final System Architecture Overview from the consolidated synthesis artifacts.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });

    it('should correctly map the "tech_stack_recommendations" step from synthesis_stage.sql', () => {
        const mockDbResponse: DatabaseRecipeSteps = {
            active_recipe_instance_id: 'instance-1',
            created_at: '2025-11-05T11:58:00.000Z',
            default_system_prompt_id: 'default-prompt',
            description: 'A stage.',
            display_name: 'Synthesis',
            expected_output_template_ids: [],
            id: 'stage-synthesis',
            recipe_template_id: 'template-synthesis',
            slug: 'synthesis',
            dialectic_stage_recipe_instances: [{
                cloned_at: null,
                created_at: '2025-11-05T11:59:00.000Z',
                id: 'instance-1',
                is_cloned: false,
                stage_id: 'stage-synthesis',
                template_id: 'template-synthesis',
                updated_at: '2025-11-05T11:59:00.000Z',
                dialectic_stage_recipe_steps: [{
                    id: 'step-synthesis-tech-stack',
                    instance_id: 'instance-1',
                    template_step_id: 'template-step-synthesis-tech-stack',
                    step_key: 'tech_stack_recommendations',
                    step_slug: 'render-tech-stack-recommendations',
                    step_name: 'Render Final Tech Stack Recommendations',
                    job_type: 'EXECUTE',
                    prompt_type: 'Turn',
                    prompt_template_id: 'prompt-synthesis-tech-stack-turn',
                    output_type: 'RenderedDocument',
                    granularity_strategy: 'all_to_one',
                    inputs_required: '[{"type":"header_context","slug":"synthesis","document_key":"header_context","required":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_technical_approach","required":true,"multiple":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_feature_spec","required":true,"multiple":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_success_metrics","required":true,"multiple":true},{"type":"document","slug":"synthesis","document_key":"synthesis_document_business_case","required":true,"multiple":true}]',
                    inputs_relevance: '[{"document_key":"header_context","slug":"synthesis","relevance":1.0},{"document_key":"synthesis_document_technical_approach","slug":"synthesis","relevance":1.0},{"document_key":"synthesis_document_feature_spec","slug":"synthesis","relevance":0.88},{"document_key":"synthesis_document_success_metrics","slug":"synthesis","relevance":0.85},{"document_key":"synthesis_document_business_case","slug":"synthesis","relevance":0.8}]',
                    outputs_required: '{"documents":[{"document_key":"tech_stack_recommendations","template_filename":"synthesis_tech_stack_recommendations.md","artifact_class":"rendered_document","file_type":"markdown","content_to_include":[{"component_name":"","recommended_option":"","rationale":"","alternatives":[],"tradeoffs":[],"risk_signals":[],"integration_requirements":[],"operational_owners":[],"migration_plan":[]}],"frontend_stack":{},"backend_stack":{},"data_platform":{},"devops_tooling":{},"security_tooling":{},"shared_libraries":[],"third_party_services":[],"open_questions":[],"next_steps":[]}]}',
                    parallel_group: 5,
                    branch_key: 'tech_stack_recommendations',
                    execution_order: 5,
                    created_at: '2025-11-06T00:00:00.000Z',
                    updated_at: '2025-11-06T00:00:00.000Z',
                    is_skipped: false,
                    config_override: {},
                    object_filter: {},
                    output_overrides: {},
                    step_description: 'Renders the final Tech Stack Recommendations from the consolidated synthesis artifacts.',
                }, ],
            }, ],
        };
        const actual = mapToStageWithRecipeSteps(mockDbResponse);
        assert(isDialecticStageRecipeStep(actual.dialectic_stage_recipe_steps[0]));
    });
});
