CREATE TABLE public.dialectic_trigger_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    log_message TEXT,
    error_details TEXT
);

COMMENT ON TABLE public.dialectic_trigger_logs IS 'Log table for debugging the dialectic_generation_jobs trigger.';

ALTER TABLE public.dialectic_trigger_logs ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.dialectic_trigger_logs TO authenticated;
GRANT ALL ON public.dialectic_trigger_logs TO service_role; 